<a href="https://colab.research.google.com/github/nedokormysh/Stepik_LLM/blob/week_4_RAG/LLM_4_2_%D0%A0%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D1%87.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ноутбук для решения задач урока 4.2

In [1]:
!pip install langchain langchain-community huggingface_hub langchain-openai openai faiss-gpu langchainhub -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 1.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 997.8/997.8 kB 22.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 42.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.9/362.9 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.9/318.9 kB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 393.9/393.9 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.1/149.1 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 37.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 3.3 MB/s eta 0:00:00

In [2]:
import os
from getpass import getpass

## Если используете ключ от OpenAI, запустите эту ячейку 👇

In [ ]:
from langchain_openai import ChatOpenAI
import os
from getpass import getpass


# os.environ['OPENAI_API_KEY'] = "Введите ваш OpenAI API ключ"
os.environ['OPENAI_API_KEY'] = getpass(prompt='Введите ваш OpenAI API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0)

## Если используете ключ из курса, запустите эти ячейки 👇

In [3]:
!wget https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py

--2024-08-23 08:09:53--  https://raw.githubusercontent.com/a-milenkin/LLM_practical_course/main/notebooks/utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11184 (11K) [text/plain]
Saving to: ‘utils.py’

utils.py            100%[===================>]  10.92K  --.-KB/s    in 0.001s

2024-08-23 08:09:53 (20.4 MB/s) - ‘utils.py’ saved [11184/11184]

In [4]:
from utils import ChatOpenAI
from getpass import getpass

#course_api_key= "Введите ваш API ключ с курса"
course_api_key = getpass(prompt='Введите API ключ')

# Инициализируем языковую модель
llm = ChatOpenAI(temperature=0.0, course_api_key=course_api_key)

Введите API ключ··········

## Задание из стэпа 6. 🪛 Openai tools Agent + RAG 🦞

Распарсив веб страницу, создадим базу знаний

In [ ]:
from langchain.document_loaders import WebBaseLoader

In [ ]:
# ссылка на страницу из Википедии про Ганнибала
url = "https://ru.wikipedia.org/wiki/%D0%93%D0%B0%D0%BD%D0%BD%D0%B8%D0%B1%D0%B0%D0%BB,_%D0%90%D0%B1%D1%80%D0%B0%D0%BC_%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D0%B8%D1%87"

In [ ]:
# Определите лоадер
loader = WebBaseLoader(url)
data = loader.load()

Засплитим данные, сформируем эмбединги и создадим ретривер

In [ ]:
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import CharacterTextSplitter
from utils import OpenAIEmbeddings

text_splitter = CharacterTextSplitter(chunk_size=2000, chunk_overlap=0)
texts = text_splitter.split_documents(data)
embeddings = OpenAIEmbeddings(course_api_key=course_api_key)

db_embed = FAISS.from_documents(texts, embeddings)

retriever = db_embed.as_retriever()

WARNING:langchain_text_splitters.base:Created a chunk of size 3163, which is longer than the specified 2000
WARNING:langchain_text_splitters.base:Created a chunk of size 2759, which is longer than the specified 2000

Инструменты для агента

In [ ]:
from langchain.tools.retriever import create_retriever_tool

tool = create_retriever_tool(
    retriever, # наш ретривер
    "search_web", # имя инструмента
    "Searches and returns data from page", # описание инструмента подается в ЛЛМ
)
tools = [tool]

In [ ]:
# Set the API key as an environment variable
os.environ['LANGCHAIN_API_KEY'] = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmJhNDg3MWMyOTMzN2VjNGRiOGIxMDIiLCJleHAiOjE3NTUwMjAyNjR9.RiYqZPH2PZyj3A3KXGUcQ6-gXNf8pvCRG_6kCn5wFIM'

In [ ]:
from langchain import hub

prompt = hub.pull("hwchase17/openai-tools-agent")
prompt

ChatPromptTemplate(input_variables=['agent_scratchpad', 'input'], optional_variables=['chat_history'], input_types={'chat_history': typing.List[typing.Union[langchain_core.messages.ai.AIMessage, langchain_core.messages.human.HumanMessage, langchain_core.messages.chat.ChatMessage, langchain_core.messages.system.SystemMessage, langchain_core.messages.function.FunctionMessage, langchain_core.messages.tool.ToolMessage]], 'agent_scratchpad': typing.List[typing.Union[langchain_core.messages.ai.AIMessage, langchain_core.messages.human.HumanMessage, langchain_core.messages.chat.ChatMessage, langchain_core.messages.system.SystemMessage, langchain_core.messages.function.FunctionMessage, langchain_core.messages.tool.ToolMessage]]}, partial_variables={'chat_history': []}, metadata={'lc_hub_owner': 'hwchase17', 'lc_hub_repo': 'openai-tools-agent', 'lc_hub_commit_hash': 'c18672812789a3b9697656dd539edf0120285dcae36396d0b548ae42a4ed66f5'}, messages=[SystemMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='You are a helpful assistant')), MessagesPlaceholder(variable_name='chat_history', optional=True), HumanMessagePromptTemplate(prompt=PromptTemplate(input_variables=['input'], template='{input}')), MessagesPlaceholder(variable_name='agent_scratchpad')])

Подключаем агента

In [ ]:
from langchain.agents import create_openai_tools_agent
from langchain.agents.agent import AgentExecutor

agent = create_openai_tools_agent(llm, tools, prompt)
agent_executor = AgentExecutor(agent=agent, tools=tools)

In [14]:
import pandas as pd
from tqdm import tqdm

In [ ]:
# Загружаем датасет с вопросами про Ганнибала
df = pd.read_csv("https://stepik.org/media/attachments/lesson/1107866/gannibal.csv")

In [ ]:
# agent_executor.invoke({"input": "длина каждого ответа не должна превышать 70 символов "})

{'input': 'длина каждого ответа не должна превышать 70 символов ',
 'output': 'Understood. How can I assist you today?'}

In [ ]:
answers = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['question']):
    answer =  agent_executor.invoke({"input": text_input})
    answers.append(answer['output']) # Добавляем ответ в список
    # break # Для отладки. Уберите, когда убедитесь, что на одном примере работает

100%|██████████| 10/10 [00:29<00:00,  2.97s/it]

In [ ]:
for n in range(len(answers)):
  print(len(answers[n]))

79
2
29
50
70
72
70
84
98
52

In [ ]:
df['answer'] = answers # Создаём новый столбец из ответов модели

In [ ]:
df

,question,answer
0,На ком в начале 1731 года Абрам Ганнибал женил...,В начале 1731 года Абрам Ганнибал женился на г...
1,Является ли А.С. Пушкин сыном Абрама Ганнибала...,Да
2,Сколько лет прожил Абрам Ганнибал? Ответ дайте...,Абрам Ганнибал прожил 85 лет.
3,В каком году Абрам Ганнибал был отправлен в Си...,Абрам Ганнибал был отправлен в Сибирь в 1727 г...
4,Куда был ранен Абрам Ганнибал участвуя в Войне...,Абрам Ганнибал был ранен в голову участвуя в В...
5,Какой размер жалования Абрам Ганнибал получал ...,В 1716 году Абрам Ганнибал получал жалование в...
6,Разграничением земель с какой страной в 1745 г...,В 1745 году Абрам Ганнибал занимался разгранич...
7,В каком звании Абрам Ганнибал был отправлен в ...,Абрам Петрович Ганнибал был отправлен в отстав...
8,Как звали вторую жену Абрама Ганнибала?,Вторая жена Абрама Ганнибала называлась Христи...
9,Сколько всего детей Абрама Ганнибала дожили до...,Четыре сына Абрама Ганнибала дожили до взрослы...

In [ ]:
df['answer'] = df['answer'].apply(lambda x: x[:70])

In [ ]:
df.to_csv('step6_solution_2.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)

In [ ]:
n = 1
print(len(df['answer'][n]))
print(df['question'][n])
print(df['answer'][n])

2
Является ли А.С. Пушкин сыном Абрама Ганнибала?. В ответе только да или нет.
Да

In [ ]:
df['answer'][1] = "Нет"

In [ ]:
df

,question,answer
0,На ком в начале 1731 года Абрам Ганнибал женил...,Евдокии Андреевне Диопер
1,Является ли А.С. Пушкин сыном Абрама Ганнибала...,Нет
2,Сколько лет прожил Абрам Ганнибал? Ответ дайте...,Абрам Ганнибал прожил 85 лет.
3,В каком году Абрам Ганнибал был отправлен в Си...,Абрам Ганнибал был отправлен в Сибирь в 1727 г...
4,Куда был ранен Абрам Ганнибал участвуя в Войне...,Абрам Ганнибал был ранен в голову участвуя в В...
5,Какой размер жалования Абрам Ганнибал получал ...,жалование в размере 100 рублей в год
6,Разграничением земель с какой страной в 1745 г...,В 1745 году Абрам Ганнибал занимался разгранич...
7,В каком звании Абрам Ганнибал был отправлен в ...,генерал-аншеф
8,Как звали вторую жену Абрама Ганнибала?,Христина-Регина фон Шёберг (Christina Regina ...
9,Сколько всего детей Абрама Ганнибала дожили до...,Четыре сына Абрама Ганнибала дожили до взрослы...

In [ ]:
df.to_csv('step6_solution_4.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)

##Задание из стэпа 9 📊Задача на SQL-агента.🕵️‍♂️

In [5]:
# Установим postgres сервер
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo service postgresql start

# установим пароль `postgres` для пользователя `postgres`
!sudo -u postgres psql -U postgres -c "ALTER USER postgres PASSWORD 'postgres';"

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 13.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package logrotate.
(Reading database ... 123595 files and directories currently installed.)
Preparing to unpack .../00-logrotate_3.19.0-1ubuntu1.1_amd64.deb ...
Unpacking logrotate (3.19.0-1ubuntu1.1) ...
Selecting previously unselected package netbase.
Preparing to unpack .../01-netbase_6.3_all.deb ...
Unpacking netbase (6.3) ...
Selecting previously unselected package libcommon-sense-perl:amd64.
Preparing to unpack .../02-libcommon-sense-perl_3.75-2build1_amd64.deb ...
Unpacking libcommon-sense-perl:amd64 (3.75-2build1) ...
Selecting previously unselected package libjson-perl.
Preparing to unpack .../03-libjson-perl_4.04000-1_all.deb ...
Unpacking libjson-perl (4.04000-1) ...
Selecting previously unselected package libtypes-serialiser-perl.
Preparing to unpack .../04-libtypes-serialiser-perl_1.01-1_all.deb ...
Unpacking libtypes-serialiser-perl (1.01-1) ...
Selecting previously unselected package libjson-xs-perl.
Preparing to unpack .../05-libjson-xs-perl_4.030-1build3_amd64.deb ...
Unpacking libjson-xs-perl (4.030-1build3) ...
Selecting previously unselected package postgresql-client-common.
Preparing to unpack .../06-postgresql-client-common_238_all.deb ...
Unpacking postgresql-client-common (238) ...
Selecting previously unselected package postgresql-client-14.
Preparing to unpack .../07-postgresql-client-14_14.13-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-client-14 (14.13-0ubuntu0.22.04.1) ...
Selecting previously unselected package ssl-cert.
Preparing to unpack .../08-ssl-cert_1.1.2_all.deb ...
Unpacking ssl-cert (1.1.2) ...
Selecting previously unselected package postgresql-common.
Preparing to unpack .../09-postgresql-common_238_all.deb ...
Adding 'diversion of /usr/bin/pg_config to /usr/bin/pg_config.libpq-dev by postgresql-common'
Unpacking postgresql-common (238) ...
Selecting previously unselected package postgresql-14.
Preparing to unpack .../10-postgresql-14_14.13-0ubuntu0.22.04.1_amd64.deb ...
Unpacking postgresql-14 (14.13-0ubuntu0.22.04.1) ...
Selecting previously unselected package postgresql.
Preparing to unpack .../11-postgresql_14+238_all.deb ...
Unpacking postgresql (14+238) ...
Selecting previously unselected package sysstat.
Preparing to unpack .../12-sysstat_12.5.2-2ubuntu0.2_amd64.deb ...
Unpacking sysstat (12.5.2-2ubuntu0.2) ...
Setting up logrotate (3.19.0-1ubuntu1.1) ...
Created symlink /etc/systemd/system/timers.target.wants/logrotate.timer → /lib/systemd/system/logrotate.timer.
Setting up libcommon-sense-perl:amd64 (3.75-2build1) ...
Setting up ssl-cert (1.1.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Setting up libtypes-serialiser-perl (1.01-1) ...
Setting up libjson-perl (4.04000-1) ...
Setting up netbase (6.3) ...
Setting up sysstat (12.5.2-2ubuntu0.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline

Creating config file /etc/default/sysstat with new version
update-alternatives: using /usr/bin/sar.sysstat to provide /usr/bin/sar (sar) in auto mode
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-collect.timer → /lib/systemd/system/sysstat-collect.timer.
Created symlink /etc/systemd/system/sysstat.service.wants/sysstat-summary.timer → /lib/systemd/system/sysstat-summary.timer.
Created symlink /etc/systemd/system/multi-user.target.wants/sysstat.service → /lib/systemd/system/sysstat.service.
Setting up postgresql-client-common (238) ...
Setting up libjson-xs-perl (4.030-1build3) ...
Setting up postgresql-client-14 (14.13-0ubuntu0.22.04.1) ...
update-alternatives: using /usr/share/postgresql/14/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode
Setting up postgresql-common (238) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Adding user postgres to group ssl-cert

Creating config file /etc/postgresql-common/createcluster.conf with new version
Building PostgreSQL dictionaries from installed myspell/hunspell packages...
Removing obsolete dictionary files:
Created symlink /etc/systemd/system/multi-user.target.wants/postgresql.service → /lib/systemd/system/postgresql.service.
Setting up postgresql-14 (14.13-0ubuntu0.22.04.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
debconf: falling back to frontend: Readline
Creating new PostgreSQL cluster 14/main ...
/usr/lib/postgresql/14/bin/initdb -D /var/lib/postgresql/14/main --auth-local peer --auth-host scram-sha-256 --no-instructions
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.UTF-8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/14/main ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok
update-alternatives: using /usr/share/postgresql/14/man/man1/postmaster.1.gz to provide /usr/share/man/man1/postmaster.1.gz (postmaster.1.gz) in auto mode
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up postgresql (14+238) ...
Processing triggers for man-db (2.10.2-1) ...
 * Starting PostgreSQL 14 database server
   ...done.
ALTER ROLE

Создаем базу, пользователя и предоставляем нужные права.

In [6]:
!sudo -u postgres psql -U postgres -c "CREATE DATABASE dvdrental;" # CREATE DATABASE
!sudo -u postgres psql -U postgres -c "create user root with encrypted password 'mypass';" # CREATE ROLE
!sudo -u postgres psql -U postgres -c "GRANT postgres TO root;" # GRANT ROLE
!sudo -u postgres psql -U postgres -c "grant all privileges on database dvdrental to root;" # GRANT

CREATE DATABASE
CREATE ROLE
GRANT ROLE
GRANT

In [7]:
# создаем базу из резервной копии
!wget https://stepik.org/media/attachments/lesson/1107866/dvdrental.tar
!sudo pg_restore -U root -d dvdrental /content/dvdrental.tar

--2024-08-23 08:11:03--  https://stepik.org/media/attachments/lesson/1107866/dvdrental.tar
Resolving stepik.org (stepik.org)... 178.248.239.111
Connecting to stepik.org (stepik.org)|178.248.239.111|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2835456 (2.7M) [application/x-tar]
Saving to: ‘dvdrental.tar’

dvdrental.tar       100%[===================>]   2.70M  2.09MB/s    in 1.3s

2024-08-23 08:11:05 (2.09 MB/s) - ‘dvdrental.tar’ saved [2835456/2835456]

In [8]:
from langchain_community.utilities import SQLDatabase

# подключимся к базе
db = SQLDatabase.from_uri("postgresql+psycopg2://root:mypass@localhost:5432/dvdrental")
print(db.dialect)

postgresql

Создаем агента и вручаем ему инструменты

In [9]:
from langchain_community.agent_toolkits import create_sql_agent
from langchain.agents.agent_toolkits import SQLDatabaseToolkit

toolkit = SQLDatabaseToolkit(db=db, llm=llm)

agent_executor = create_sql_agent(llm,
                         toolkit=toolkit,
                         verbose=True)

In [15]:
import pandas as pd
from tqdm import tqdm

In [12]:
# Загружаем датасет с вопросами к базе
df = pd.read_csv("https://stepik.org/media/attachments/lesson/1107866/rental_dvd.csv")

In [19]:
answers = [] # Список, где будем хранить ответы модели

for text_input in tqdm(df['question']):
    answer = agent_executor.invoke({"input": text_input})
    answers.append(answer['output']) # Добавляем ответ в список
    # break # Для отладки. Уберите, когда убедитесь, что на одном примере работает

  0%|          | 0/5 [00:00<?, ?it/s]

> Entering new SQL Agent Executor chain...
Action: sql_db_list_tables
Action Input: actor, address, category, city, country, customer, film, film_actor, film_category, inventory, language, payment, rental, staff, storeThe most relevant table for customer information is likely the customer table. I should query the schema of the customer table.
Action: sql_db_schema
Action Input: customer
CREATE TABLE customer (
	customer_id SERIAL NOT NULL,
	store_id SMALLINT NOT NULL,
	first_name VARCHAR(45) NOT NULL,
	last_name VARCHAR(45) NOT NULL,
	email VARCHAR(50),
	address_id SMALLINT NOT NULL,
	activebool BOOLEAN DEFAULT true NOT NULL,
	create_date DATE DEFAULT ('now'::text)::date NOT NULL,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
	active INTEGER,
	CONSTRAINT customer_pkey PRIMARY KEY (customer_id),
	CONSTRAINT customer_address_id_fkey FOREIGN KEY(address_id) REFERENCES address (address_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from customer table:
customer_id	store_id	first_name	last_name	email	address_id	activebool	create_date	last_update	active
524	1	Jared	Ely	jared.ely@sakilacustomer.org	530	True	2006-02-14	2013-05-26 14:49:45.738000	1
1	1	Mary	Smith	mary.smith@sakilacustomer.org	5	True	2006-02-14	2013-05-26 14:49:45.738000	1
2	1	Patricia	Johnson	patricia.johnson@sakilacustomer.org	6	True	2006-02-14	2013-05-26 14:49:45.738000	1
*/I have the schema and sample rows from the customer table. I can now construct a query to find the email of the customer Enrique Forsythe.
Action: sql_db_query
Action Input: SELECT email FROM customer WHERE first_name = 'Enrique' AND last_name = 'Forsythe'[('enrique.forsythe@sakilacustomer.org',)]

 20%|██        | 1/5 [00:04<00:18,  4.66s/it]

The email of the customer Enrique Forsythe is enrique.forsythe@sakilacustomer.org
Final Answer: enrique.forsythe@sakilacustomer.org

> Finished chain.


> Entering new SQL Agent Executor chain...
Action: sql_db_list_tables
Action Input: actor, address, category, city, country, customer, film, film_actor, film_category, inventory, language, payment, rental, staff, storeThe relevant tables for this question are film and film_category. I should query the schema of these tables to see which columns contain the rating information.
Action: sql_db_schema
Action Input: film, film_category
CREATE TABLE film (
	film_id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	release_year year,
	language_id SMALLINT NOT NULL,
	rental_duration SMALLINT DEFAULT 3 NOT NULL,
	rental_rate NUMERIC(4, 2) DEFAULT 4.99 NOT NULL,
	length SMALLINT,
	replacement_cost NUMERIC(5, 2) DEFAULT 19.99 NOT NULL,
	rating mpaa_rating DEFAULT 'G'::mpaa_rating,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	special_features TEXT[],
	fulltext TSVECTOR NOT NULL,
	CONSTRAINT film_pkey PRIMARY KEY (film_id),
	CONSTRAINT film_language_id_fkey FOREIGN KEY(language_id) REFERENCES language (language_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from film table:
film_id	title	description	release_year	language_id	rental_duration	rental_rate	length	replacement_cost	rating	last_update	special_features	fulltext
133	Chamber Italian	A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria	2006	1	7	4.99	117	14.99	NC-17	2013-05-26 14:50:58.951000	['Trailers']	'chamber':1 'fate':4 'husband':11 'italian':2 'monkey':16 'moos':8 'must':13 'nigeria':18 'overcom':
384	Grosse Wonderful	A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia	2006	1	5	4.99	49	19.99	R	2013-05-26 14:50:58.951000	['Behind the Scenes']	'australia':18 'cat':8 'drama':5 'epic':4 'explor':11 'gross':1 'moos':16 'must':13 'redeem':14 'won
8	Airport Pollock	A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India	2006	1	6	4.99	54	15.99	R	2013-05-26 14:50:58.951000	['Trailers']	'airport':1 'ancient':18 'confront':14 'epic':4 'girl':11 'india':19 'monkey':16 'moos':8 'must':13
*/


CREATE TABLE film_category (
	film_id SMALLINT NOT NULL,
	category_id SMALLINT NOT NULL,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT film_category_pkey PRIMARY KEY (film_id, category_id),
	CONSTRAINT film_category_category_id_fkey FOREIGN KEY(category_id) REFERENCES category (category_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT film_category_film_id_fkey FOREIGN KEY(film_id) REFERENCES film (film_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from film_category table:
film_id	category_id	last_update
1	6	2006-02-15 10:07:09
2	11	2006-02-15 10:07:09
3	6	2006-02-15 10:07:09
*/The rating information is stored in the "rating" column of the "film" table. I can join the "film" and "film_category" tables on the "film_id" column to get the ratings of films in the collection.
Action: sql_db_query
Action Input: SELECT f.rating, COUNT(*) as rating_count
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
GROUP BY f.rating
ORDER BY rating_count DESC
LIMIT 10;[('PG-13', 223), ('NC-17', 210), ('R', 195), ('PG', 194), ('G', 178)]

 40%|████      | 2/5 [00:09<00:14,  4.73s/it]

I now know the final answer.
Final Answer: PG-13 rated films predominate in the collection.

> Finished chain.


> Entering new SQL Agent Executor chain...
Action: sql_db_list_tables
Action Input: actor, address, category, city, country, customer, film, film_actor, film_category, inventory, language, payment, rental, staff, storeThe tables that seem relevant are actor and film. I should query the schema of these tables to see what columns are available.
Action: sql_db_schema
Action Input: actor, film
CREATE TABLE actor (
	actor_id SERIAL NOT NULL,
	first_name VARCHAR(45) NOT NULL,
	last_name VARCHAR(45) NOT NULL,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT actor_pkey PRIMARY KEY (actor_id)
)

/*
3 rows from actor table:
actor_id	first_name	last_name	last_update
1	Penelope	Guiness	2013-05-26 14:47:57.620000
2	Nick	Wahlberg	2013-05-26 14:47:57.620000
3	Ed	Chase	2013-05-26 14:47:57.620000
*/


CREATE TABLE film (
	film_id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	release_year year,
	language_id SMALLINT NOT NULL,
	rental_duration SMALLINT DEFAULT 3 NOT NULL,
	rental_rate NUMERIC(4, 2) DEFAULT 4.99 NOT NULL,
	length SMALLINT,
	replacement_cost NUMERIC(5, 2) DEFAULT 19.99 NOT NULL,
	rating mpaa_rating DEFAULT 'G'::mpaa_rating,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	special_features TEXT[],
	fulltext TSVECTOR NOT NULL,
	CONSTRAINT film_pkey PRIMARY KEY (film_id),
	CONSTRAINT film_language_id_fkey FOREIGN KEY(language_id) REFERENCES language (language_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from film table:
film_id	title	description	release_year	language_id	rental_duration	rental_rate	length	replacement_cost	rating	last_update	special_features	fulltext
133	Chamber Italian	A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria	2006	1	7	4.99	117	14.99	NC-17	2013-05-26 14:50:58.951000	['Trailers']	'chamber':1 'fate':4 'husband':11 'italian':2 'monkey':16 'moos':8 'must':13 'nigeria':18 'overcom':
384	Grosse Wonderful	A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia	2006	1	5	4.99	49	19.99	R	2013-05-26 14:50:58.951000	['Behind the Scenes']	'australia':18 'cat':8 'drama':5 'epic':4 'explor':11 'gross':1 'moos':16 'must':13 'redeem':14 'won
8	Airport Pollock	A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India	2006	1	6	4.99	54	15.99	R	2013-05-26 14:50:58.951000	['Trailers']	'airport':1 'ancient':18 'confront':14 'epic':4 'girl':11 'india':19 'monkey':16 'moos':8 'must':13
*/I can see that the relevant columns for the question are the film title in the film table and the actor's first and last name in the actor table. I should query the database to find the shortest film with Johnny Lollobrigida as an actor.
Action: sql_db_query
Action Input: SELECT film.title, actor.first_name, actor.last_name
FROM film
JOIN film_actor ON film.film_id = film_actor.film_id
JOIN actor ON film_actor.actor_id = actor.actor_id
WHERE actor.first_name = 'Johnny' AND actor.last_name = 'Lollobrigida'
ORDER BY LENGTH(film.title)
LIMIT 1;[('Pocus Pulp', 'Johnny', 'Lollobrigida')]

 60%|██████    | 3/5 [00:14<00:09,  4.95s/it]

I now know the final answer.
Final Answer: The shortest film with actor Johnny Lollobrigida is "Pocus Pulp".

> Finished chain.


> Entering new SQL Agent Executor chain...
Action: sql_db_list_tables
Action Input: actor, address, category, city, country, customer, film, film_actor, film_category, inventory, language, payment, rental, staff, storeI should check the 'staff' table to find information about employees.
Action: sql_db_schema
Action Input: staff
CREATE TABLE staff (
	staff_id SERIAL NOT NULL,
	first_name VARCHAR(45) NOT NULL,
	last_name VARCHAR(45) NOT NULL,
	address_id SMALLINT NOT NULL,
	email VARCHAR(50),
	store_id SMALLINT NOT NULL,
	active BOOLEAN DEFAULT true NOT NULL,
	username VARCHAR(16) NOT NULL,
	password VARCHAR(40),
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	picture BYTEA,
	CONSTRAINT staff_pkey PRIMARY KEY (staff_id),
	CONSTRAINT staff_address_id_fkey FOREIGN KEY(address_id) REFERENCES address (address_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from staff table:
staff_id	first_name	last_name	address_id	email	store_id	active	username	password	last_update	picture
1	Mike	Hillyer	3	Mike.Hillyer@sakilastaff.com	1	True	Mike	8cb2237d0679ca88db6464eac60da96345513964	2006-05-16 16:13:11.793280	b'\x89PNG\r\nZ\n'
2	Jon	Stephens	4	Jon.Stephens@sakilastaff.com	2	True	Jon	8cb2237d0679ca88db6464eac60da96345513964	2006-05-16 16:13:11.793280	None
*/I can now construct a query to find out the country of the employee Mike Hillyer.
Action: sql_db_query
Action Input: SELECT country.country FROM country
JOIN city ON country.country_id = city.country_id
JOIN address ON city.city_id = address.city_id
JOIN staff ON address.address_id = staff.address_id
WHERE staff.first_name = 'Mike' AND staff.last_name = 'Hillyer';[('Canada',)]

 80%|████████  | 4/5 [00:19<00:04,  4.80s/it]

I now know the final answer
Final Answer: Сотрудник Mike Hillyer из Канады.

> Finished chain.


> Entering new SQL Agent Executor chain...
Action: sql_db_list_tables
Action Input: actor, address, category, city, country, customer, film, film_actor, film_category, inventory, language, payment, rental, staff, storeThe relevant tables for this question are film and rental. I should query the schema of these tables to see which columns I can use.
Action: sql_db_schema
Action Input: film, rental
CREATE TABLE film (
	film_id SERIAL NOT NULL,
	title VARCHAR(255) NOT NULL,
	description TEXT,
	release_year year,
	language_id SMALLINT NOT NULL,
	rental_duration SMALLINT DEFAULT 3 NOT NULL,
	rental_rate NUMERIC(4, 2) DEFAULT 4.99 NOT NULL,
	length SMALLINT,
	replacement_cost NUMERIC(5, 2) DEFAULT 19.99 NOT NULL,
	rating mpaa_rating DEFAULT 'G'::mpaa_rating,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	special_features TEXT[],
	fulltext TSVECTOR NOT NULL,
	CONSTRAINT film_pkey PRIMARY KEY (film_id),
	CONSTRAINT film_language_id_fkey FOREIGN KEY(language_id) REFERENCES language (language_id) ON DELETE RESTRICT ON UPDATE CASCADE
)

/*
3 rows from film table:
film_id	title	description	release_year	language_id	rental_duration	rental_rate	length	replacement_cost	rating	last_update	special_features	fulltext
133	Chamber Italian	A Fateful Reflection of a Moose And a Husband who must Overcome a Monkey in Nigeria	2006	1	7	4.99	117	14.99	NC-17	2013-05-26 14:50:58.951000	['Trailers']	'chamber':1 'fate':4 'husband':11 'italian':2 'monkey':16 'moos':8 'must':13 'nigeria':18 'overcom':
384	Grosse Wonderful	A Epic Drama of a Cat And a Explorer who must Redeem a Moose in Australia	2006	1	5	4.99	49	19.99	R	2013-05-26 14:50:58.951000	['Behind the Scenes']	'australia':18 'cat':8 'drama':5 'epic':4 'explor':11 'gross':1 'moos':16 'must':13 'redeem':14 'won
8	Airport Pollock	A Epic Tale of a Moose And a Girl who must Confront a Monkey in Ancient India	2006	1	6	4.99	54	15.99	R	2013-05-26 14:50:58.951000	['Trailers']	'airport':1 'ancient':18 'confront':14 'epic':4 'girl':11 'india':19 'monkey':16 'moos':8 'must':13
*/


CREATE TABLE rental (
	rental_id SERIAL NOT NULL,
	rental_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	inventory_id INTEGER NOT NULL,
	customer_id SMALLINT NOT NULL,
	return_date TIMESTAMP WITHOUT TIME ZONE,
	staff_id SMALLINT NOT NULL,
	last_update TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL,
	CONSTRAINT rental_pkey PRIMARY KEY (rental_id),
	CONSTRAINT rental_customer_id_fkey FOREIGN KEY(customer_id) REFERENCES customer (customer_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT rental_inventory_id_fkey FOREIGN KEY(inventory_id) REFERENCES inventory (inventory_id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT rental_staff_id_key FOREIGN KEY(staff_id) REFERENCES staff (staff_id)
)

/*
3 rows from rental table:
rental_id	rental_date	inventory_id	customer_id	return_date	staff_id	last_update
2	2005-05-24 22:54:33	1525	459	2005-05-28 19:40:33	1	2006-02-16 02:30:53
3	2005-05-24 23:03:39	1711	408	2005-06-01 22:12:39	1	2006-02-16 02:30:53
4	2005-05-24 23:04:41	2452	333	2005-06-03 01:43:41	2	2006-02-16 02:30:53
*/I can join the film and rental tables on the film_id and inventory_id columns to get the rental_rate of films that last less than an hour. I will calculate the average rental_rate for these films.
Action: sql_db_query
Action Input: SELECT AVG(f.rental_rate)
FROM film f
JOIN rental r ON f.film_id = r.inventory_id
WHERE f.length < 60[(Decimal('2.8273493975903614'),)]

100%|██████████| 5/5 [00:23<00:00,  4.80s/it]

The average rental rate of films that last less than an hour is approximately 2.83.
Final Answer: The average rental rate of films that last less than an hour is approximately 2.83.

> Finished chain.

In [18]:
answer

{'input': 'Какой e-mail у клиента Enrique Forsythe?',
 'output': 'enrique.forsythe@sakilacustomer.org'}

In [20]:
df['answer'] = answers # Создаём новый столбец из ответов модели

In [21]:
df.to_csv('step_9_solution.csv', index=False) # Сохраняем файл, отправляем на Stepik, получаем баллы :)